# Site settings
title: "The Grimoire"
author: "Saph, thebombzen"
description:
  "A searchable D&D 5e spell list, sorted by class and level."
permalink: "/:categories/:title"
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

# Build settings
markdown: kramdown
highlighter: pygments

# Site defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "spells"
